name: CI

on: [push]

jobs:
  ci_on_push:
    concurrency:
      group: ${{ github.ref }}
      cancel-in-progress: true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0

      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: ~/.yarn
          key: ${{ runner.OS }}-node-modules-v2-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.OS }}-node-modules-v2

      - name: Install dependencies
        run: yarn install

      - name: Lint
        run: yarn run lint
